Feat port setting
johnolafenwa/DeepStack pull request #107
Opened 2021-07-09 20:32 UTC by AbimbolaOO

2021-07-14 21:53 UTC, johnolafenwa requested changes
Great work on this.
Please add back the EXPOSE 5000
While the expose command doesn't perform any function in a technical sense, the idea of it is that you can look at a Dockerfile and tell the port on which to run it without having to look at the source code of the app.

2021-07-16 10:01 UTC, AbimbolaOO commented
> Great work on this.
> Please add back the EXPOSE 5000
> While the expose command doesn't perform any function in a technical sense, the idea of it is that you can look at a Dockerfile and tell the port on which to run it without having to look at the source code of the app.

The reason I removed it was because It prevented me from setting Deepstack internal port successfully via the use of environmental variables. Can add back the line but comment it at the same time?

2021-07-16 10:14 UTC, OlafenwaMoses commented
> > Great work on this.
> > Please add back the EXPOSE 5000
> > While the expose command doesn't perform any function in a technical sense, the idea of it is that you can look at a Dockerfile and tell the port on which to run it without having to look at the source code of the app.
> 
> The reason I removed it was because It prevented me from setting Deepstack internal port successfully via the use of environmental variables. Can add back the line but comment it at the same time?

Don't comment it. Leave it as is.

2021-07-25 13:35 UTC, johnolafenwa approved these changes

2021-07-25 13:36 UTC, merged